#include<stdio.h>
int main () {
  printf("I AM A ROBOT I AM A ROBOT I AM A ROBOT AND I LIKE TO DANCE");
  printf("I AM A ROBOT I AM A ROBOT I AM A ROBOT AND I LIKE TO DANCE");
  printf("I AM A ROBOT I AM A ROBOT I AM A ROBOT AND I LIKE TO DANCE");
}
